models = {}
include('l1-direct.lua')
include('l1-interaction.lua')
include('l1-interaction-direct.lua')
include('l2-interaction.lua')
include('l2-interaction-direct.lua')
include('l2-direct.lua')
include('l1-mono.lua')
include('l2-mono.lua')
include('cosine_wrapper.lua')
